### ISSUE TITLE
Best way of reporting these metrics to Graphite?

### ISSUE THREAD

**Issue by ojilles** [mikejihbe/metrics#16]
Is there a canonical/best way of reporting the measured metrics to graphite?

**Comment by tolbertam** [comment]
I've written implementations of csv and graphite reporting that inherit from ScheduledReporter.  They follow the same output format as codahale/dropwizard metrics.  I've been using it for a few months now and haven't any issues.  Is there any interest in this?  If so I can log a PR.

**Comment by jakubholynet** [comment]
@tolbertam I would certainly be interested in at least having a look at your Graphite reporter (to find out how best to write my InfluxDB reporter). Please share!

**Comment by jakubholynet** [comment]
I have just discovered there is a `metrics-influxdb` for repporting from Metrics to InfluxDB. I have added a new wiki page for this project with key info from this discussion - https://github.com/mikejihbe/metrics/wiki

**Comment by mikejihbe** [comment]
Thanks for the contributions guys. @tolbertam go ahead and make the PR, let's get that in here

**Comment by tolbertam** [comment]
My apologies for the lack of response, my email filter went on a the fritz and auto archived these messages.  I'll post my GraphiteReporter shortly for those interested

**Comment by tolbertam** [comment]
[Here](https://gist.github.com/tolbertam/e54a979d355f9e2df9d5) is a gist of 3 reporters i've constructed.  I'll work on a PR this weekend to incorporate these in.

**Comment by tolbertam** [comment]
Thanks for sharing `metrics-influxdb` @jakubholynet!  I'll take a look at their implementation and see if there are some ideas in there I can adapt to mine.

**Comment by tolbertam** [comment]
Got a little caught up a couple weekends ago, working on this today

**Comment by jakubholynet** [comment]
Since #29 has been merged, this issue can perhaps be closed, no?

**Comment by tolbertam** [comment]
Agreed that this is fixed by #29, closing 👍
