### ISSUE TITLE
Question: is there a ready-made visual front end for data?

### ISSUE THREAD

**Issue by paul42** [mikejihbe/metrics#41]
Just wondering if you have any visual frontends for this data, or ways that are good at pulling this in?

thanks in advance,
Paul

**Comment by tolbertam** [comment]
Hi @paul42, not provided by the metrics library itself.  What I do is use [`GraphiteReporter`](https://github.com/mikejihbe/metrics/blob/master/reporting/graphite-reporter.js) to send metrics to a graphite instance and then use [Grafana](http://grafana.org/) to provide a visual front end to my metrics.  It works really well and provides some nice visualizations.

**Comment by tolbertam** [comment]
Closing but feel free to reopen if you'd like more details on that 👍

**Comment by paul42** [comment]
nope, pretty well explained! do you off the top of your head recommend a service for hosting graphite, or do you usually just spin up a vm on aws or the like and host it there? Thanks again!

**Comment by tolbertam** [comment]
Apologies for the late reply, didn't notice your response until now!    I would recommend self-hosting in your environment as it isn't too bad to run a graphite instance.  Things start becoming complex when you need to scale graphite out or need high availability.   I've never gotten to that point (in past I have fired up a larger instance whenever things get rough) so don't have a good recommendation for a hosted graphite solution.
